# Generated by Django 5.1.4 on 2025-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_category_color_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
