# Generated by Django 5.1.4 on 2025-04-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
