# Generated by Django 5.1.3 on 2025-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0008_category_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="lists_sort_order",
            field=models.CharField(
                choices=[
                    ("created", "Più recente"),
                    ("alphabetical", "Alfabetico"),
                    ("complete", "Per completezza"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
