# Generated by Django 5.1.3 on 2025-10-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0011_profile_bio_profile_first_name_profile_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
