# Generated by Django 5.1.3 on 2025-10-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0013_listcategory_category_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category_sort_alpha",
            field=models.BooleanField(default=False),
        ),
    ]
